<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.4 
# *Python with MongoDB*

## Introduction to PyMongo

In [1]:
from IPython.core.display import display, HTML
import pymongo
from pymongo import MongoClient
print ('Mongo version ' + pymongo.__version__)

Mongo version 3.12.0


/var/folders/jk/1cws__yn4bbfzktv83sdj85w0000gn/T/ipykernel_47959/1201951307.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


Start the mongod server (if it isn't lready running) by executing  
`mongod`  
at the command prompt. 

In [124]:
client = MongoClient('localhost', 27017)

In [125]:
db = client.test
collection = db.people
collection.drop()

Create a new database:

In [126]:
mydb = client["mydatabase"]

Confirm that the database exists ... 

- list all databases in your system:

In [127]:
mydb

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'mydatabase')

- check for the database by name:

The new database was not found because mongodb is lazy: the db won't get created until data has been written to it!

Create a collection called "customers" (with object name `mycol`):

In [128]:
#ANSWER:
mycol = mydb["customers"]

Create a document (i.e. a dictionary) with two name:value items 
("name" = "John", and "address" = "Highway 37") and insert 
it into the "customers" collection: 

In [129]:
#ANSWER:
mydict = { "name": "John", "address": "Highway 37" }
x = mycol.insert_one(mydict)

Now test for the existence of the database:

In [130]:
print(client.list_database_names())

['admin', 'config', 'local', 'mydatabase']


List all collections in the database:

In [131]:
#ANSWER:
print(mydb.list_collection_names())

['customers']


Insert another record in the "customers" collection 
("name" = "Peter", "address" = "Lowstreet 27") 
and return the value of the _id field:

In [132]:
#ANSWER:
mydict = { "name": "Peter", "address": "Lowstreet 27" }
x = mycol.insert_one(mydict)
print(x.inserted_id)

63e0be1123f85a2d0aea2a3e


Given the list of dicts below, insert multiple documents into 
the collection using the insert_many() method:

In [134]:
mylist = [
  { "name": "Amy", "address": "Apple st 652"},
  { "name": "Hannah", "address": "Mountain 21"},
  { "name": "Michael", "address": "Valley 345"},
  { "name": "Sandy", "address": "Ocean blvd 2"},
  { "name": "Betty", "address": "Green Grass 1"},
  { "name": "Richard", "address": "Sky st 331"},
  { "name": "Susan", "address": "One way 98"},
  { "name": "Vicky", "address": "Yellow Garden 2"},
  { "name": "Ben", "address": "Park Lane 38"},
  { "name": "William", "address": "Central st 954"},
  { "name": "Chuck", "address": "Main Road 989"},
  { "name": "Viola", "address": "Sideway 1633"}
]

In [135]:
#ANSWER:
x = mycol.insert_many(mylist)

Print a list of the _id values of the inserted documents:

In [136]:
#ANSWER:
print(x.inserted_ids)

[ObjectId('63e0be2123f85a2d0aea2a3f'), ObjectId('63e0be2123f85a2d0aea2a40'), ObjectId('63e0be2123f85a2d0aea2a41'), ObjectId('63e0be2123f85a2d0aea2a42'), ObjectId('63e0be2123f85a2d0aea2a43'), ObjectId('63e0be2123f85a2d0aea2a44'), ObjectId('63e0be2123f85a2d0aea2a45'), ObjectId('63e0be2123f85a2d0aea2a46'), ObjectId('63e0be2123f85a2d0aea2a47'), ObjectId('63e0be2123f85a2d0aea2a48'), ObjectId('63e0be2123f85a2d0aea2a49'), ObjectId('63e0be2123f85a2d0aea2a4a')]


Execute the next cell to insert a list of dicts with specified `_id`s:

In [137]:
mylist = [
  { "_id": 1, "name": "John", "address": "Highway 37"},
  { "_id": 2, "name": "Peter", "address": "Lowstreet 27"},
  { "_id": 3, "name": "Amy", "address": "Apple st 652"},
  { "_id": 4, "name": "Hannah", "address": "Mountain 21"},
  { "_id": 5, "name": "Michael", "address": "Valley 345"},
  { "_id": 6, "name": "Sandy", "address": "Ocean blvd 2"},
  { "_id": 7, "name": "Betty", "address": "Green Grass 1"},
  { "_id": 8, "name": "Richard", "address": "Sky st 331"},
  { "_id": 9, "name": "Susan", "address": "One way 98"},
  { "_id": 10, "name": "Vicky", "address": "Yellow Garden 2"},
  { "_id": 11, "name": "Ben", "address": "Park Lane 38"},
  { "_id": 12, "name": "William", "address": "Central st 954"},
  { "_id": 13, "name": "Chuck", "address": "Main Road 989"},
  { "_id": 14, "name": "Viola", "address": "Sideway 1633"}
]
x = mycol.insert_many(mylist)
print(x.inserted_ids)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


Now try inserting a new dict with an existing `_id`:

In [138]:
x = mycol.insert_one({ "_id": 14, "name": "Manuel", "address": "Barcelona"})

DuplicateKeyError: E11000 duplicate key error collection: mydatabase.customers index: _id_ dup key: { _id: 14 }, full error: {'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: mydatabase.customers index: _id_ dup key: { _id: 14 }', 'keyPattern': {'_id': 1}, 'keyValue': {'_id': 14}}

In [139]:
x = mycol.find_one({"name": "Manuel"})
print(x)

{'_id': 15, 'name': 'Manuel', 'address': 'Barcelona'}


So, if we want to manage `_id`s in code, we need to be careful!

This returns the first document in the collection:

In [140]:
x = mycol.find_one()
print(x)

{'_id': ObjectId('63e0ae4623f85a2d0aea2a2b'), 'name': 'John', 'address': 'Highway 37'}


Do the same for the document containing "name" = "Hannah":

In [141]:
#ANSWER:
x = mycol.find_one({"name": "Hannah"})
print(x)

{'_id': ObjectId('63e0be2123f85a2d0aea2a40'), 'name': 'Hannah', 'address': 'Mountain 21'}


This returns (and prints) all documents in the collection:

In [142]:
for x in mycol.find():
  print(x)

{'_id': ObjectId('63e0ae4623f85a2d0aea2a2b'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('63e0ae6e23f85a2d0aea2a2c'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2d'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2f'), 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a30'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a31'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a32'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a33'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a34'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a35'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a36'), 'name': 'William', 'address': 'Central st 954'}
{'_id': Obj

This returns only the name and address fields:

In [143]:
for x in mycol.find({},{ "_id": 0, "name": 1, "address": 1 }):
  print(x)

{'name': 'John', 'address': 'Highway 37'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Amy', 'address': 'Apple st 652'}
{'name': 'Michael', 'address': 'Canyon 123'}
{'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'name': 'Betty', 'address': 'Green Grass 1'}
{'name': 'Richard', 'address': 'Sky st 331'}
{'name': 'Susan', 'address': 'One way 98'}
{'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'name': 'Ben', 'address': 'Park Lane 38'}
{'name': 'William', 'address': 'Central st 954'}
{'name': 'Chuck', 'address': 'Main Road 989'}
{'name': 'Viola', 'address': 'Sideway 1633'}
{'name': 'Manuel', 'address': 'Barcelona'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Amy', 'address': 'Apple st 652'}
{'name': 'Hannah', 'address': 'Mountain 21'}
{'name': 'Michael', 'address': 'Valley 345'}
{'name': 'Sandy', 'address

Print only the `_id` and name fields:

In [144]:
#ANSWER:
for x in mycol.find({},{ "_id": 1, "name": 1 }):
  print(x)

{'_id': ObjectId('63e0ae4623f85a2d0aea2a2b'), 'name': 'John'}
{'_id': ObjectId('63e0ae6e23f85a2d0aea2a2c'), 'name': 'Peter'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2d'), 'name': 'Amy'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2f'), 'name': 'Michael'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a30'), 'name': 'Sandy'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a31'), 'name': 'Betty'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a32'), 'name': 'Richard'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a33'), 'name': 'Susan'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a34'), 'name': 'Vicky'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a35'), 'name': 'Ben'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a36'), 'name': 'William'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a37'), 'name': 'Chuck'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a38'), 'name': 'Viola'}
{'_id': 15, 'name': 'Manuel'}
{'_id': ObjectId('63e0b6b223f85a2d0aea2a39'), 'name': 'John'}
{'_id': ObjectId('63e0b6e723f85a2d0aea2a3a'), 'name': 'John'}
{'_id': ObjectId('63e0bc13

So, we must explicitly use `"_id": 0` to exclude it, but for other fields we simply omit them from the dict argument.

To include field conditionals in a query, we use `$` operators. This finds addresses starting with "S" or greater:

In [145]:
myquery = { "address": { "$gt": "S" } }
mydoc = mycol.find(myquery)
for x in mydoc:
  print(x)

{'_id': ObjectId('63e0ae7a23f85a2d0aea2a32'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a34'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a38'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a41'), 'name': 'Michael', 'address': 'Valley 345'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a44'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a46'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a4a'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 8, 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': 10, 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': 14, 'name': 'Viola', 'address': 'Sideway 1633'}


Here are some more comparison operators:

            $gt, $gte, $eq, $in, $nin, $exists, $and, $or, $not
            
Experiment with these until you understand how to use them.

In [146]:
myquery = { "name": { "$gte": "P" } }
mydoc = mycol.find(myquery)
for x in mydoc:
  print(x)

{'_id': ObjectId('63e0ae6e23f85a2d0aea2a2c'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a30'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a32'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a33'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a34'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a36'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a38'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63e0be1123f85a2d0aea2a3e'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a42'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a44'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a45'), 'name': 'Susan', 'address': 'One way 98'}
{'_id':

Now find all docs with an address that begins with "S":  
(HINT: The value for "address" in the argument should be the regex-based dict { "$regex": "^S" }.)

In [147]:
#ANSWER:
myquery = { "address": { "$regex": "^S" } }
mydoc = mycol.find(myquery)
for x in mydoc:
  print(x)

{'_id': ObjectId('63e0ae7a23f85a2d0aea2a32'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a38'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a44'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a4a'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': 8, 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': 14, 'name': 'Viola', 'address': 'Sideway 1633'}


Sorting can be applied by invoking the Sort() method after the Find() method. Sort the collection by the name field:

In [148]:
#ANSWER:
mydoc = mycol.find().sort("name")
for x in mydoc:
  print(x)

{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2d'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a3f'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a35'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a47'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': 11, 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a31'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a43'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': 7, 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a37'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a49'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': 13, 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a40'), 'name': 'Hannah', 

Now sort in reverse order (HINT: The Sort() method takes an optional second parameter.)

In [149]:
#ANSWER:
mydoc = mycol.find().sort("name", direction=pymongo.DESCENDING)
for x in mydoc:
  print(x)

{'_id': ObjectId('63e0ae7a23f85a2d0aea2a36'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a48'), 'name': 'William', 'address': 'Central st 954'}
{'_id': 12, 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a38'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a4a'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': 14, 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a34'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a46'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': 10, 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a33'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('63e0be2123f85a2d0aea2a45'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': 9, 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a30

A single record can be deleted by specifying some criterion:

In [150]:
mycol.delete_one({ "address": "Mountain 21" })

Now delete all docs with the 2-digit `Id` values:

In [155]:
#ANSWER:
mycol.delete_many({ "_id": {"$lt": 15} })
for x in mycol.find():
  print(x)

{'_id': ObjectId('63e0ae4623f85a2d0aea2a2b'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('63e0ae6e23f85a2d0aea2a2c'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2d'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2f'), 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a30'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a31'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a32'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a33'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a34'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a35'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a36'), 'name': 'William', 'address': 'Central st 954'}
{'_id': Obj

This would delete all docs:
`x = mycol.delete_many({})`

This would remove the collection:
`mycol.drop()`

Change the first instance of "address" == "Valley 345" to "Canyon 123" using update_one().  
(HINT: The 1st paramater of update_one() is the criterion (query); the 2nd is dict specifying the field to change and its new value.) 

In [156]:
#ANSWER:
myquery = { "address": "Valley 345" }
newvalues = { "$set": { "address": "Canyon 123" } }
mycol.update_one(myquery, newvalues)
for x in mycol.find():
  print(x)

{'_id': ObjectId('63e0ae4623f85a2d0aea2a2b'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('63e0ae6e23f85a2d0aea2a2c'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2d'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2f'), 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a30'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a31'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a32'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a33'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a34'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a35'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a36'), 'name': 'William', 'address': 'Central st 954'}
{'_id': Obj

The limit() method can be applied after the find() method to limit the number of docs returned. Show the first 5 docs:

In [157]:
#ANSWER:
myresult = mycol.find().limit(5)
for x in myresult:
  print(x)

{'_id': ObjectId('63e0ae4623f85a2d0aea2a2b'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('63e0ae6e23f85a2d0aea2a2c'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2d'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2f'), 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a30'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}


## PyMongo for Data Science

MongoDB has many more features of interest to developers, but the main focus of a data scientist will be wrangling and munging the data. It may or may not be desirable to do all the data munging in Pandas; for a large, distributed database, it may be imperative to perform aggregation in MongoDB. 

In [49]:
# Ref:  https://rsandstroem.github.io/MongoDBDemo.html

import os
import pandas as pd
import numpy as np

This code creates a database named "test" and populates it from a JSON file using the mongoimport program (executed in the operating systems itself, rather than in Python):

In [50]:
db = client.test
# Drop the collection in case it was previously created:
# collection = db.people
# collection.drop()

In [52]:
pwd()

'/Users/Vagner/Documents/IOD_Projects/Module3/Labs 3'

In [61]:
# if this does not return 0, execute mongoimport from a commmand window instead:
os.system('mongoimport -d test -c people --file dummyData.json')

2023-02-06T21:02:10.102+1300	Failed: open dummyData.json: no such file or directory
2023-02-06T21:02:10.103+1300	0 document(s) imported successfully. 0 document(s) failed to import.


256

In [64]:
db = client.test
collection = db.people
cursor = collection.find().sort('Age',pymongo.ASCENDING).limit(3)
for doc in cursor:
    print (doc)

{'_id': ObjectId('63e0b40c1fcc1d0c84fcb19c'), 'Name': 'Sawyer, Neve M.', 'Age': 18, 'Country': 'Serbia', 'Location': '-34.37446, 174.0838'}
{'_id': ObjectId('63e0b40c1fcc1d0c84fcb159'), 'Name': 'Townsend, Cadman I.', 'Age': 19, 'Country': 'Somalia', 'Location': '-87.69188, -144.16138'}
{'_id': ObjectId('63e0b40c1fcc1d0c84fcb184'), 'Name': 'Graham, Emerald O.', 'Age': 20, 'Country': 'Eritrea', 'Location': '61.35398, 28.04381'}


Here is a small demonstration of the MongoDB aggregation framework. We want to create a table of the number of persons in each country and their average age. To do it we group by country. We extract the results from MongoDB aggregation into a pandas dataframe, and use the country as index.

In [65]:
pipeline = [
        {"$group": {"_id":"$Country",
             "AvgAge":{"$avg":"$Age"},
             "Count":{"$sum":1},
        }},
        {"$sort":{"Count":-1,"AvgAge":1}}
]
aggResult = collection.aggregate(pipeline) # returns a cursor

df1 = pd.DataFrame(list(aggResult)) # use list to turn the cursor to an array of documents
df1 = df1.set_index("_id")
df1.head()

AvgAge  Count
_id                                                
China                              46.250000      4
Antarctica                         46.333333      3
Guernsey                           48.333333      3
Puerto Rico                        26.500000      2
Heard Island and Mcdonald Islands  29.000000      2

For simple cases one can either use a cursor through find("search term") or use the "$match" operator in the aggregation framework, like this:

In [66]:
pipeline = [
        {"$match": {"Country":"China"}},
]
aggResult = collection.aggregate(pipeline)
df2 = pd.DataFrame(list(aggResult))
df2.head()

_id                Name  Age Country  \
0  63e0b40c1fcc1d0c84fcb16b    Holman, Hasad O.   32   China   
1  63e0b40c1fcc1d0c84fcb197      Byrd, Dante A.   43   China   
2  63e0b40c1fcc1d0c84fcb19e  Carney, Tamekah I.   57   China   
3  63e0b40c1fcc1d0c84fcb1ad    Mayer, Violet U.   53   China   

            Location  
0  39.9127, 116.3833  
1        31.2, 121.5  
2    45.75, 126.6333  
3             40, 95

Now we can apply all the power of Python libraries to analyse and visualise the data. Here, we will use the folium package to plot markers for the locations of the people we just found in China (click on a marker to see their data):

In [ ]:
# Un-comment and execute to install folium pkg (1st time only):
# import sys
# !{sys.executable} -m pip install folium

In [67]:
import folium
print ('Folium version ' + folium.__version__)

world_map = folium.Map(location = [35, 100], zoom_start = 4)
for i in range(len(df2)):
    location = [float(loc) for loc in df2.Location[i].split(',')]
    folium.Marker(location = location, popup = df2.Name[i] + ', age:' + str(df2.Age[i])).add_to(world_map)
    
world_map

Folium version 0.13.0


## HOMEWORK:


1. Read up on how to perform aggregation in mongoDB. Insert a duplicate record into the collection:
        mydict = { "name": "John", "address": "Highway 37" }
   Now write a command to find docs with a duplicate "name" field (using aggregation) and remove them.  
   Print the collection.

In [102]:
collection = db.people
collection.drop()

In [103]:
db = client.test
collection = db.people

In [108]:
print(client.list_database_names())

['admin', 'config', 'local', 'mydatabase']


In [109]:
#ANSWER:
print(mydb.list_collection_names())

['customers']


In [158]:
for x in mycol.find({},{ "_id": 0, "name": 1, "address": 1 }):
  print(x)

{'name': 'John', 'address': 'Highway 37'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Amy', 'address': 'Apple st 652'}
{'name': 'Michael', 'address': 'Canyon 123'}
{'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'name': 'Betty', 'address': 'Green Grass 1'}
{'name': 'Richard', 'address': 'Sky st 331'}
{'name': 'Susan', 'address': 'One way 98'}
{'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'name': 'Ben', 'address': 'Park Lane 38'}
{'name': 'William', 'address': 'Central st 954'}
{'name': 'Chuck', 'address': 'Main Road 989'}
{'name': 'Viola', 'address': 'Sideway 1633'}
{'name': 'Manuel', 'address': 'Barcelona'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Amy', 'address': 'Apple st 652'}
{'name': 'Michael', 'address': 'Canyon 123'}
{'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'name': 'Betty', 'address

In [159]:
mydict = { "name": "John", "address": "Highway 37" }
x = mycol.insert_one(mydict)
print(x.inserted_id)

63e0bea423f85a2d0aea2a4b


In [160]:
for x in mycol.find({},{ "_id": 1, "name": 1 }):
  print(x)

{'_id': ObjectId('63e0ae4623f85a2d0aea2a2b'), 'name': 'John'}
{'_id': ObjectId('63e0ae6e23f85a2d0aea2a2c'), 'name': 'Peter'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2d'), 'name': 'Amy'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a2f'), 'name': 'Michael'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a30'), 'name': 'Sandy'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a31'), 'name': 'Betty'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a32'), 'name': 'Richard'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a33'), 'name': 'Susan'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a34'), 'name': 'Vicky'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a35'), 'name': 'Ben'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a36'), 'name': 'William'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a37'), 'name': 'Chuck'}
{'_id': ObjectId('63e0ae7a23f85a2d0aea2a38'), 'name': 'Viola'}
{'_id': 15, 'name': 'Manuel'}
{'_id': ObjectId('63e0b6b223f85a2d0aea2a39'), 'name': 'John'}
{'_id': ObjectId('63e0b6e723f85a2d0aea2a3a'), 'name': 'John'}
{'_id': ObjectId('63e0bc13

In [167]:
aggResult = collection.aggregate([
    {"$group" : { "_id": "$name", "count": { "$sum": 1 } } },
    {"$match": {  "count" : {"$gt": 1} } } , 
    {"$project": {"name" : "$_id", "_id" : 0} } 
]);
df3 = pd.DataFrame(list(aggResult))
df3.head()

Empty DataFrame
Columns: []
Index: []

2. Read up on how to apply indexes in mongoDB. Create an index on the "name" and "address" fields in this collection.
   Print the indexes for the collection.

In [166]:
db.customers.createIndex({name: 1, address: 1})

NameError: name 'name' is not defined



> 
>
>






---



---



> > > > > > > > > © 2022 Institute of Data


---



---



